name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  # To add the built application to the release, we need to write to the contents permission.
  # https://www.electronforge.io/config/publishers/github#authentication
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Setup Git
        run: |
          git config --global user.name "${GITHUB_USER}"
          git config --global user.email "${GITHUB_USER}@users.noreply.github.com"
        env:
          GITHUB_USER: github-actions[bot]
      
      - name: Bump version
        id: version
        run: |
          npm version ${{ github.event.inputs.version_type }}
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Build for x64
        run: npm run make -- --platform=darwin --arch=x64
      
      - name: Build for arm64
        run: npm run make -- --platform=darwin --arch=arm64
      
      - name: Push tags
        run: git push --tags
      
      - name: Create GitHub Release
        run: |
          gh release create v${{ steps.version.outputs.new_version }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to GitHub Releases
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
