name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  # To add the built application to the release, we need to write to the contents permission.
  # https://www.electronforge.io/config/publishers/github#authentication
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish application
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

